AddFictionChapterCommentPayload:
  type: relay-mutation-payload
  config:
    fields:
      fictionChapterComment:
        type: FictionChapterComment!
        description: The newly fiction chapter comment
