DeleteCommentInput:
  type: relay-mutation-input
  config:
    description: Input type of deleteComment
    fields:
      commentId:
        description: The comment ID which is going to be deleted
        type: ID!