FictionComment:
  type: object
  inherits: [Comment]
  config:
    interfaces: [Comment, Node]
    description: A comment in a fiction
    fields:
      fiction:
        description: The related fiction associated to this comment
        type: Fiction!
