FictionOrderField:
  type: enum
  config:
    description: Properties by which fictions can be ordered
    values:
      CREATED_AT:
        value: createdAt
        description: Allows ordering a list of fictions by when they were created
      CHAPTERS_COUNT:
        value: chaptersCount
        description: Allows ordering a list of fictions by their chapters count