FictionChapter:
  type: object
  inherits: [Node, Timestampable]
  config:
    interfaces: [Node]
    description: A fiction chapter.
    fields:
      title:
        type: String!
        description: The fiction chapter title
      slug:
        type: String!
        description: The fiction chapter slug
      body:
        type: String!
        description: The fiction chapter body
      position:
        type: Int!
        description: The fiction chapter position
      comments:
        type: FictionChapterCommentConnection!
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Fiction\\Chapter\\FictionChapterCommentsResolver", [value, args])'
        argsBuilder: Relay::Connection
        args:
          first:
            type: Int
            defaultValue: 20
          orderBy:
            type: FictionCommentOrder
            defaultValue: { field: createdAt, direction: DESC }
      rootComments:
        type: FictionChapterCommentConnection!
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Fiction\\Chapter\\FictionChapterRootCommentsResolver", [value, args])'
        argsBuilder: Relay::Connection
        args:
          first:
            type: Int
            defaultValue: 20
          orderBy:
            type: FictionCommentOrder
            defaultValue: { field: createdAt, direction: DESC }