Mutation:
  type: object
  config:
    fields:
      addComment:
        access: '@=hasRole("ROLE_USER")'
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: AddCommentInput
          payloadType: AddCommentPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\Comment\\AddCommentMutation", [value, getUser()])'
      addAnswerComment:
        access: '@=hasRole("ROLE_USER")'
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: AddAnswerCommentInput
          payloadType: AddAnswerCommentPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\Comment\\AddAnswerCommentMutation", [value, getUser()])'
      deleteComment:
        access: '@=hasRole("ROLE_USER")'
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: DeleteCommentInput
          payloadType: DeleteCommentPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\Comment\\DeleteCommentMutation", [value])'